version: "3.6"
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    restart: always
    networks:
      - alert
    volumes:
      - db_data:/var/lib/postgresql/alert_data
    environment:
      POSTGRES_DB: alert
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: img_alert
    container_name: alert
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DB_USER=${DB_USER}
        - DB_PW=${DB_PW}
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_NAME=${DB_NAME}
    depends_on:
      - "postgres"
    restart: always
    networks:
      - alert
volumes:
  db_data:
networks:
  alert:
    name: alert_network
