version: "3.6"
services:
  postgres:
    image: postgres:12-alpine
    restart: always
    networks:
      - alert
    environment:
      POSTGRES_DB: alert
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
  alert_center:
    image: img_alert_center
    container_name: alert_center
    depends_on:
      - "postgres"
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DB_USER=${DB_USER}
        - DB_PW=${DB_PW}
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_NAME=${DB_NAME}
    depends_on:
      - "postgres"
    restart: always
    networks:
      - alert

networks:
  alert:
    name: alert_network
